services:
  - type: web
    name: box-upload-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOX_CLIENT_ID
        value: q2v4q1m4yq7qkn149l3vrf8hi6d8mzrx
      - key: BOX_CLIENT_SECRET
        value: AKssvX4W0K3nq79G845rG6vSsp3yTnNA
      - key: BOX_PUBLIC_KEY_ID
        value: f43yf8zj
      - key: BOX_PASSPHRASE
        value: 7834e3e416b5390d72e56600e59592ac
      - key: BOX_ENTERPRISE_ID
        value: "0"
      - key: BOX_FOLDER_ID
        value: "375842438354"
      - key: BOX_PRIVATE_KEY
        sync: false
